### ISSUE TITLE
composer 安装提示找不到代码

### ISSUE THREAD

**Issue by gantoday** [isszz/think-blade#2]
![image](https://user-images.githubusercontent.com/7780154/101485745-90136580-3996-11eb-938a-21599148f5a0.png)

去composer代码仓库看了 确实没有这个库
大佬是不是忘记传到composer仓库了
建议上传下。谢谢。

**Comment by isszz** [comment]
= =... 那个我还没弄

**Comment by isszz** [comment]
A package with the name isszz/think-blade already exists.
应该是你传了,我这个重复了- -...
